### ISSUE TITLE
Missing TypeScript definition

### ISSUE THREAD

**Issue by ilteoood** [vanodevium/fastify-qs#53]
The plugin has a [type definition](https://github.com/vanodevium/fastify-qs/blob/master/plugin.d.ts), which is not available in the NPM package:
![image](https://user-images.githubusercontent.com/6383527/235853578-2a57feec-44f3-4d97-a892-93d5fa98d7de.png)

The result is the following:
![image](https://user-images.githubusercontent.com/6383527/235853647-c3879f1e-da8f-4a91-b9ca-3eb2343f4096.png)

**Comment by vanodevium** [comment]
@ilteoood 
Please update your dependency version to [v4.0.2](https://www.npmjs.com/package/fastify-qs/v/4.0.2)

If there are any difficulties, please feel free to comment
