### ISSUE TITLE
Not compatible with Fastify v5

### ISSUE THREAD

**Issue by plavaga-rc** [vanodevium/fastify-qs#54]
Hi,
Thanks for this excellent plugin. I am one of the users for the same.

The current version of fastify-qs does not work with Fastify v5, but only till v4.

Can you please update the plugin to make it compatible with Fastify v5?

**Comment by vanodevium** [comment]
@plavaga-rc 

Sorry for the delay!

[5.0.0](https://www.npmjs.com/package/fastify-qs/v/5.0.0)
